docs: add test case details and sample data for verifier tests
eclipse-tractusx/ssi-docu pull request #19
Opened 2023-07-11 11:22 UTC by paullatzelsperger

## WHAT

adds test specification and some sample test data for verifier tests. Issuer tests will follow in another PR, as well as more test data/.

## WHY

to have a specified test set for verifier tests

2023-07-11 11:40 UTC, paullatzelsperger commented
\cc @jimmarino

2023-07-20 09:36 UTC, maximilianschmidt-zf requested changes
The BpnCredential Type doesent have CX in it

2023-07-20 09:36 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0003.a_vc_embedded_forged_claim.json
> +    "https://org.eclipse.tractusx/businessPartnerData",
```suggestion
    "https://org.eclipse.tractusx/businessPartnerData.json",
```
Because of the github pages issue it should be with .json I think

2023-07-20 09:36 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0003.b_vc_embedded_altered_credentialsubject.json
> +    "BpnCredentialCX"
```suggestion
    "BpnCredential"
```

2023-07-20 09:36 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0003.c_vc_embedded_altered_claim.json
> +      "BpnCredentialCX"
```suggestion
      "BpnCredential"
```

2023-07-20 09:36 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0004.a_vc_embedded_forged_proof.json
> +    "BpnCredentialCX"
```suggestion
    "BpnCredential"
```

2023-07-20 09:36 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0004.b_vc_embedded_invalid_proof.json
> +      "BpnCredentialCX"
```suggestion
      "BpnCredential"
```

2023-07-20 09:36 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0005_vc_canonicalization.json
> +    "BpnCredentialCX"
```suggestion
    "BpnCredential"
```

2023-07-20 09:36 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0010_vp_compacted.json
> +      "BpnCredentialCX"
```suggestion
      "BpnCredential"
```

2023-07-20 09:36 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0002_valid_vc_embedded_proof.json
> +      "BpnCredentialCX"
```suggestion
      "BpnCredential"
```

2023-07-20 09:36 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0001_valid_vc_linked_proof.json
> +      "BpnCredentialCX"
```suggestion
      "BpnCredential"
```

2023-08-02 08:23 UTC, wolf4ood commented on docs/testkit/sample_input/v-t_0001_valid_vc_linked_proof.json
> +      "type": "https://org.eclipse.tractusx/businessPartnerData#BpnCredential"
From [here](https://github.com/eclipse-tractusx/ssi-docu/blob/main/docs/credentials/tx.vc.guidelines.md) 
it should be catenax label. Also we should grab the a persistent `catenax` identifier on [w3id](https://w3id.org/)

2023-08-02 11:48 UTC, maximilianschmidt-zf requested changes
Hey I think there is a typo happend at proof and the bpn credential

2023-08-02 11:48 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0001_valid_vc_linked_proof.json
> +    "sec:proof": {
```suggestion
    "proof": {
```

2023-08-02 11:48 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0002_valid_vc_embedded_proof.json
> +    "sec:proof": {
```suggestion
    "proof": {
```

2023-08-02 11:48 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0003.a_vc_embedded_forged_claim.json
> +  "sec:proof": {
```suggestion
  "proof": {
```

2023-08-02 11:48 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0003.b_vc_embedded_altered_credentialsubject.json
> +  "sec:proof": {
```suggestion
  "proof": {
```

2023-08-02 11:48 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0003.c_vc_embedded_altered_claim.json
> +    "sec:proof": {
```suggestion
    "proof": {
```

2023-08-02 11:48 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0004.a_vc_embedded_forged_proof.json
> +  "sec:proof": {
```suggestion
  "proof": {
```

2023-08-02 11:48 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0004.b_vc_embedded_invalid_proof.json
> +    "sec:proof": {
```suggestion
    "proof": {
```

2023-08-02 11:48 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0005_vc_canonicalization.json
> +  "sec:proof": {
```suggestion
  "proof": {
```

2023-08-02 11:48 UTC, maximilianschmidt-zf commented on docs/testkit/sample_input/v-t_0010_vp_compacted.json
> +  "sec:proof": {
```suggestion
  "proof": {
```

2023-08-02 12:21 UTC, paullatzelsperger commented
> Hey I think there is a typo happend at proof and the bpn credential

yep correct. i just copy-pasted it...

2023-08-07 12:50 UTC, paullatzelsperger commented
merging, as all comments have been addressed, and re-reviews are open for multiple days

2023-08-07 12:50 UTC, merged